import type { Product } from '@/types'
import { Timestamp } from 'firebase/firestore'

const now = Timestamp.now()

export const SEED_PRODUCTS: Product[] = [
  // ROSES
  {
    id: 'prod-001',
    name: 'Velvet Red Romance',
    slug: 'velvet-red-romance',
    description: 'A breathtaking dozen of premium long-stem red roses, symbolising deep love and passion.',
    longDescription: 'Our signature arrangement of twelve exquisite long-stem red roses, each carefully selected for their velvety petals and intoxicating fragrance. Presented in our luxury gift box with hand-tied ribbon and complementary flower food. The ultimate expression of love.',
    price: 89.99,
    compareAtPrice: 109.99,
    category: 'roses',
    categoryName: 'Roses',
    occasions: ['romance', 'anniversary', 'birthday'],
    flowerTypes: ['roses'],
    tags: ['red roses', 'romance', 'luxury', 'bestseller'],
    images: [
      { url: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=800&q=80', alt: 'Velvet Red Romance bouquet', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=800&q=80', alt: 'Red roses close-up', isPrimary: false },
    ],
    variants: [
      { id: 'v1', name: 'Standard (12 stems)', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe (24 stems)', priceModifier: 45, inStock: true },
      { id: 'v3', name: 'Luxury (50 stems)', priceModifier: 110, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 50,
    allowsSameDay: true,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 127,
    searchTerms: 'velvet red romance roses dozen long stem love passion luxury',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-002',
    name: 'Blush Pink Elegance',
    slug: 'blush-pink-elegance',
    description: 'Delicate pink roses in graduating shades, a vision of grace and femininity.',
    longDescription: 'An enchanting collection of pink roses in soft blush tones, artfully arranged to create a stunning gradient effect. Perfect for celebrating the women in your life or adding a touch of elegance to any space.',
    price: 74.99,
    category: 'roses',
    categoryName: 'Roses',
    occasions: ['birthday', 'thank-you', 'congratulations'],
    flowerTypes: ['roses'],
    tags: ['pink roses', 'elegant', 'feminine', 'gradient'],
    images: [
      { url: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=800&q=80', alt: 'Blush Pink Elegance bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 30, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 35,
    allowsSameDay: true,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 89,
    searchTerms: 'blush pink elegance roses feminine grace gradient',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-003',
    name: 'Ivory White Serenity',
    slug: 'ivory-white-serenity',
    description: 'Pure white roses arranged with eucalyptus for a serene, sophisticated display.',
    longDescription: 'A heavenly arrangement of pristine white roses complemented by fragrant eucalyptus and delicate gypsophila. Ideal for sympathy, weddings, or anyone who appreciates timeless beauty.',
    price: 69.99,
    category: 'roses',
    categoryName: 'Roses',
    occasions: ['sympathy', 'wedding', 'thank-you'],
    flowerTypes: ['roses', 'eucalyptus'],
    tags: ['white roses', 'sympathy', 'wedding', 'serene'],
    images: [
      { url: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=800&q=80', alt: 'Ivory White Serenity', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 25, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 40,
    allowsSameDay: true,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 63,
    searchTerms: 'ivory white serenity roses eucalyptus sympathy wedding pure',
    createdAt: now,
    updatedAt: now,
  },

  // MIXED BOUQUETS
  {
    id: 'prod-004',
    name: 'Spring Awakening',
    slug: 'spring-awakening',
    description: 'A vibrant celebration of spring with tulips, daffodils, and hyacinths in joyful hues.',
    longDescription: 'Welcome the season with this exuberant bouquet featuring fresh tulips in sunset shades, cheerful daffodils, and fragrant hyacinths. A burst of colour and scent that captures the very essence of spring.',
    price: 54.99,
    category: 'mixed-bouquets',
    categoryName: 'Mixed Bouquets',
    occasions: ['birthday', 'thank-you', 'get-well', 'congratulations'],
    flowerTypes: ['tulips', 'daffodils', 'hyacinths'],
    tags: ['spring', 'colourful', 'seasonal', 'cheerful'],
    images: [
      { url: 'https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=800&q=80', alt: 'Spring Awakening bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 20, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 45,
    allowsSameDay: true,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 94,
    searchTerms: 'spring awakening tulips daffodils hyacinths colourful seasonal',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-005',
    name: 'Wildflower Meadow',
    slug: 'wildflower-meadow',
    description: 'A charming, rustic arrangement inspired by English country meadows.',
    longDescription: 'Loose, natural, and utterly charming. This hand-tied bouquet brings the beauty of an English meadow indoors with cornflowers, daisies, snapdragons, and delicate grasses. Perfect for nature lovers and free spirits.',
    price: 49.99,
    category: 'mixed-bouquets',
    categoryName: 'Mixed Bouquets',
    occasions: ['birthday', 'thank-you', 'new-baby'],
    flowerTypes: ['wildflowers', 'daisies', 'cornflowers'],
    tags: ['wildflower', 'rustic', 'country', 'natural'],
    images: [
      { url: 'https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=800&q=80', alt: 'Wildflower Meadow bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 20, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 30,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 72,
    searchTerms: 'wildflower meadow rustic country daisies cornflowers natural english',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-006',
    name: 'Sunset Glow',
    slug: 'sunset-glow',
    description: 'Warm oranges, corals, and golds create a radiant arrangement reminiscent of golden hour.',
    longDescription: 'Bask in the warm glow of this stunning bouquet featuring orange garden roses, coral carnations, golden chrysanthemums, and amber hypericum berries. A radiant display that fills any room with warmth.',
    price: 59.99,
    category: 'mixed-bouquets',
    categoryName: 'Mixed Bouquets',
    occasions: ['birthday', 'congratulations', 'thank-you'],
    flowerTypes: ['roses', 'carnations', 'chrysanthemums'],
    tags: ['orange', 'warm', 'sunset', 'golden'],
    images: [
      { url: 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=800&q=80', alt: 'Sunset Glow bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 25, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 25,
    allowsSameDay: true,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 58,
    searchTerms: 'sunset glow orange coral gold warm radiant',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-007',
    name: 'Pastel Dreams',
    slug: 'pastel-dreams',
    description: 'Soft pastels of lilac, peach, and mint create a dreamy, ethereal bouquet.',
    longDescription: 'A delicate confection of pastel-hued blooms including lisianthus, stock, sweet peas, and spray roses in the softest shades. Like a watercolour painting brought to life.',
    price: 64.99,
    category: 'mixed-bouquets',
    categoryName: 'Mixed Bouquets',
    occasions: ['birthday', 'new-baby', 'get-well', 'thank-you'],
    flowerTypes: ['lisianthus', 'sweet peas', 'roses'],
    tags: ['pastel', 'soft', 'dreamy', 'delicate'],
    images: [
      { url: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=800&q=80', alt: 'Pastel Dreams bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 25, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 20,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 81,
    searchTerms: 'pastel dreams lilac peach mint soft dreamy ethereal lisianthus',
    createdAt: now,
    updatedAt: now,
  },

  // LUXURY
  {
    id: 'prod-008',
    name: 'The Grand Gesture',
    slug: 'the-grand-gesture',
    description: '100 premium roses in a bespoke hat box — the ultimate statement of love.',
    longDescription: 'For moments that demand the extraordinary. One hundred of our finest Ecuadorian roses, meticulously arranged in our signature velvet-lined hat box. Available in classic red, romantic pink, or pure white. Includes luxury ribbon and a handwritten card.',
    price: 249.99,
    compareAtPrice: 299.99,
    category: 'luxury',
    categoryName: 'Luxury',
    occasions: ['romance', 'anniversary', 'wedding'],
    flowerTypes: ['roses'],
    tags: ['luxury', '100 roses', 'hat box', 'statement', 'premium'],
    images: [
      { url: 'https://images.unsplash.com/photo-1494972308805-463bc619d34e?w=800&q=80', alt: 'The Grand Gesture - 100 roses', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Classic Red', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Romantic Pink', priceModifier: 0, inStock: true },
      { id: 'v3', name: 'Pure White', priceModifier: 0, inStock: true },
    ],
    size: 'luxury',
    inStock: true,
    stockQuantity: 10,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 5.0,
    reviewCount: 34,
    searchTerms: 'grand gesture 100 roses hat box luxury statement ecuadorian premium',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-009',
    name: 'Opulent Orchid Collection',
    slug: 'opulent-orchid-collection',
    description: 'Exotic phalaenopsis orchids in a stunning ceramic vessel — pure sophistication.',
    longDescription: 'Three cascading phalaenopsis orchids in shades of white and mauve, presented in a handcrafted ceramic vessel. This living arrangement brings weeks of beauty and makes an unforgettable gift for those with discerning taste.',
    price: 129.99,
    category: 'luxury',
    categoryName: 'Luxury',
    occasions: ['anniversary', 'congratulations', 'thank-you'],
    flowerTypes: ['orchids'],
    tags: ['orchids', 'luxury', 'exotic', 'long-lasting'],
    images: [
      { url: 'https://images.unsplash.com/photo-1566873535350-a3f5d4a804b7?w=800&q=80', alt: 'Opulent Orchid Collection', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Single Stem', priceModifier: -50, inStock: true },
      { id: 'v2', name: 'Triple Stem', priceModifier: 0, inStock: true },
    ],
    size: 'large',
    inStock: true,
    stockQuantity: 15,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 45,
    searchTerms: 'opulent orchid collection phalaenopsis exotic luxury ceramic sophistication',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-010',
    name: 'Peony Paradise',
    slug: 'peony-paradise',
    description: 'Luxurious seasonal peonies in soft pinks and creams — a fleeting treasure.',
    longDescription: 'The queen of flowers, available for a limited season only. Our hand-selected peonies in the most exquisite shades of blush, coral, and cream. Each stem opens to reveal layer upon layer of ruffled petals. A truly special gift.',
    price: 99.99,
    category: 'luxury',
    categoryName: 'Luxury',
    occasions: ['birthday', 'anniversary', 'romance', 'wedding'],
    flowerTypes: ['peonies'],
    tags: ['peonies', 'luxury', 'seasonal', 'limited'],
    images: [
      { url: 'https://images.unsplash.com/photo-1562690868-60bbe7293e94?w=800&q=80', alt: 'Peony Paradise bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard (10 stems)', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Luxury (20 stems)', priceModifier: 60, inStock: true },
    ],
    size: 'large',
    inStock: true,
    stockQuantity: 12,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: true,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 56,
    searchTerms: 'peony paradise peonies luxury seasonal pink cream blush limited',
    createdAt: now,
    updatedAt: now,
  },

  // PLANTS
  {
    id: 'prod-011',
    name: 'Peace Lily',
    slug: 'peace-lily',
    description: 'An elegant peace lily in a contemporary pot — the perfect living gift.',
    longDescription: 'The beloved Spathiphyllum, known for its glossy leaves and graceful white flowers, presented in a sleek ceramic pot. Low-maintenance, air-purifying, and beautiful year-round. Includes care card.',
    price: 39.99,
    category: 'plants',
    categoryName: 'Plants',
    occasions: ['sympathy', 'new-baby', 'thank-you', 'get-well'],
    flowerTypes: ['peace lily'],
    tags: ['plant', 'indoor', 'air-purifying', 'low-maintenance'],
    images: [
      { url: 'https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=800&q=80', alt: 'Peace Lily plant', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Small', priceModifier: -10, inStock: true },
      { id: 'v2', name: 'Medium', priceModifier: 0, inStock: true },
      { id: 'v3', name: 'Large', priceModifier: 20, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 30,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 42,
    searchTerms: 'peace lily plant indoor air purifying low maintenance spathiphyllum',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-012',
    name: 'Monstera Deliciosa',
    slug: 'monstera-deliciosa',
    description: 'The iconic Swiss cheese plant — a statement piece for any modern home.',
    longDescription: 'A lush, healthy Monstera Deliciosa with characteristically split leaves. This tropical beauty thrives indoors and grows into a spectacular specimen plant. Presented in a premium terracotta pot.',
    price: 54.99,
    category: 'plants',
    categoryName: 'Plants',
    occasions: ['congratulations', 'thank-you'],
    flowerTypes: ['monstera'],
    tags: ['plant', 'indoor', 'tropical', 'statement'],
    images: [
      { url: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&q=80', alt: 'Monstera Deliciosa plant', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Medium', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Large', priceModifier: 30, inStock: true },
    ],
    size: 'large',
    inStock: true,
    stockQuantity: 20,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 38,
    searchTerms: 'monstera deliciosa swiss cheese plant indoor tropical statement',
    createdAt: now,
    updatedAt: now,
  },

  // HAMPERS
  {
    id: 'prod-013',
    name: 'Flowers & Fizz',
    slug: 'flowers-and-fizz',
    description: 'A gorgeous bouquet paired with a bottle of premium Prosecco — cheers to that!',
    longDescription: 'The perfect celebration duo: a hand-tied bouquet of roses, freesias, and eucalyptus paired with a 75cl bottle of premium Italian Prosecco. Beautifully presented in our signature gift box.',
    price: 79.99,
    category: 'hampers',
    categoryName: 'Hampers',
    occasions: ['birthday', 'congratulations', 'anniversary', 'thank-you'],
    flowerTypes: ['roses', 'freesias'],
    tags: ['hamper', 'prosecco', 'celebration', 'gift set'],
    images: [
      { url: 'https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?w=800&q=80', alt: 'Flowers & Fizz hamper', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'With Prosecco', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'With Champagne', priceModifier: 30, inStock: true },
    ],
    size: 'large',
    inStock: true,
    stockQuantity: 25,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 67,
    searchTerms: 'flowers fizz prosecco champagne celebration hamper gift set',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-014',
    name: 'Chocolate & Blooms',
    slug: 'chocolate-and-blooms',
    description: 'Indulgent Belgian chocolates paired with a beautiful hand-tied bouquet.',
    longDescription: 'A decadent pairing of our seasonal hand-tied bouquet with a luxury box of handmade Belgian chocolates. The ultimate indulgence for someone special.',
    price: 69.99,
    category: 'hampers',
    categoryName: 'Hampers',
    occasions: ['birthday', 'romance', 'thank-you', 'get-well'],
    flowerTypes: ['mixed'],
    tags: ['hamper', 'chocolate', 'belgian', 'indulgent'],
    images: [
      { url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', alt: 'Chocolate & Blooms hamper', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 25, inStock: true },
    ],
    size: 'large',
    inStock: true,
    stockQuantity: 20,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 53,
    searchTerms: 'chocolate blooms belgian indulgent hamper gift',
    createdAt: now,
    updatedAt: now,
  },

  // LETTERBOX
  {
    id: 'prod-015',
    name: 'Letterbox Sunshine',
    slug: 'letterbox-sunshine',
    description: 'Bright, cheerful stems delivered flat through the letterbox — a happy surprise!',
    longDescription: 'No need to be home! This carefully curated selection of sunflowers, chrysanthemums, and solidago is packaged flat to slip through any standard letterbox. Simply unwrap, trim, and arrange. Includes flower food and care instructions.',
    price: 29.99,
    category: 'letterbox',
    categoryName: 'Letterbox',
    occasions: ['birthday', 'thank-you', 'get-well', 'congratulations'],
    flowerTypes: ['sunflowers', 'chrysanthemums'],
    tags: ['letterbox', 'sunshine', 'convenient', 'no-one-home'],
    images: [
      { url: 'https://images.unsplash.com/photo-1444021465936-c6ca81d39b84?w=800&q=80', alt: 'Letterbox Sunshine flowers', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
    ],
    size: 'small',
    inStock: true,
    stockQuantity: 60,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.5,
    reviewCount: 112,
    searchTerms: 'letterbox sunshine sunflowers convenient delivery flat post',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-016',
    name: 'Letterbox Lavender Bliss',
    slug: 'letterbox-lavender-bliss',
    description: 'Soothing lavender tones in a letterbox-friendly package — calm delivered.',
    longDescription: 'A serene selection of purple lisianthus, lavender statice, and silvery eucalyptus, carefully packaged to fit through your letterbox. A peaceful gift that arrives as a lovely surprise.',
    price: 32.99,
    category: 'letterbox',
    categoryName: 'Letterbox',
    occasions: ['thank-you', 'get-well', 'sympathy'],
    flowerTypes: ['lisianthus', 'statice'],
    tags: ['letterbox', 'lavender', 'calming', 'purple'],
    images: [
      { url: 'https://images.unsplash.com/photo-1561181286-d3fee7d55364?w=800&q=80', alt: 'Letterbox Lavender Bliss', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
    ],
    size: 'small',
    inStock: true,
    stockQuantity: 45,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 78,
    searchTerms: 'letterbox lavender bliss purple calming lisianthus statice',
    createdAt: now,
    updatedAt: now,
  },

  // MORE MIXED BOUQUETS
  {
    id: 'prod-017',
    name: 'New Baby Joy',
    slug: 'new-baby-joy',
    description: 'A soft, joyful arrangement in gentle yellows and whites to welcome the little one.',
    longDescription: 'Celebrate the arrival of a precious new life with this tender arrangement of cream roses, yellow freesias, and white daisies, finished with soft greenery. Gender-neutral and utterly charming.',
    price: 52.99,
    category: 'mixed-bouquets',
    categoryName: 'Mixed Bouquets',
    occasions: ['new-baby', 'congratulations'],
    flowerTypes: ['roses', 'freesias', 'daisies'],
    tags: ['new baby', 'yellow', 'white', 'gentle', 'celebration'],
    images: [
      { url: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=800&q=80', alt: 'New Baby Joy bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 20, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 25,
    allowsSameDay: true,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 41,
    searchTerms: 'new baby joy yellow white gentle celebration newborn',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-018',
    name: 'Sympathy Embrace',
    slug: 'sympathy-embrace',
    description: 'A graceful tribute in soft whites and greens, expressing heartfelt condolences.',
    longDescription: 'A dignified and comforting arrangement of white lilies, white roses, and lush foliage. This thoughtful tribute conveys deepest sympathy with elegance and grace. Hand-delivered with care.',
    price: 64.99,
    category: 'mixed-bouquets',
    categoryName: 'Mixed Bouquets',
    occasions: ['sympathy'],
    flowerTypes: ['lilies', 'roses'],
    tags: ['sympathy', 'condolence', 'white', 'tribute', 'funeral'],
    images: [
      { url: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=800&q=80', alt: 'Sympathy Embrace arrangement', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 30, inStock: true },
      { id: 'v3', name: 'Premium Wreath', priceModifier: 55, inStock: true },
    ],
    size: 'large',
    inStock: true,
    stockQuantity: 20,
    allowsSameDay: true,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 37,
    searchTerms: 'sympathy embrace condolence white tribute funeral lilies roses',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-019',
    name: 'Tropical Paradise',
    slug: 'tropical-paradise',
    description: 'Exotic birds of paradise, protea, and anthuriums in a bold, tropical display.',
    longDescription: 'Transport someone to warmer climes with this dramatic arrangement of birds of paradise, king protea, and vibrant anthuriums. A show-stopping centrepiece that lasts and lasts.',
    price: 84.99,
    category: 'luxury',
    categoryName: 'Luxury',
    occasions: ['birthday', 'congratulations'],
    flowerTypes: ['birds of paradise', 'protea', 'anthuriums'],
    tags: ['tropical', 'exotic', 'bold', 'dramatic', 'long-lasting'],
    images: [
      { url: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=800&q=80', alt: 'Tropical Paradise bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 35, inStock: true },
    ],
    size: 'large',
    inStock: true,
    stockQuantity: 15,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 29,
    searchTerms: 'tropical paradise birds paradise protea anthuriums exotic bold',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'prod-020',
    name: 'English Garden',
    slug: 'english-garden',
    description: 'A classic English garden arrangement with peonies, roses, and sweet peas.',
    longDescription: 'Inspired by the great English gardens, this romantic arrangement combines garden roses, peonies, sweet peas, and jasmine vine. Each bouquet is a unique masterpiece reflecting the beauty of the season.',
    price: 74.99,
    category: 'mixed-bouquets',
    categoryName: 'Mixed Bouquets',
    occasions: ['birthday', 'anniversary', 'romance', 'wedding'],
    flowerTypes: ['roses', 'peonies', 'sweet peas'],
    tags: ['english garden', 'romantic', 'classic', 'seasonal'],
    images: [
      { url: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=800&q=80', alt: 'English Garden bouquet', isPrimary: true },
    ],
    variants: [
      { id: 'v1', name: 'Standard', priceModifier: 0, inStock: true },
      { id: 'v2', name: 'Deluxe', priceModifier: 30, inStock: true },
    ],
    size: 'medium',
    inStock: true,
    stockQuantity: 18,
    allowsSameDay: false,
    allowsNextDay: true,
    isFeatured: false,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 64,
    searchTerms: 'english garden romantic classic peonies roses sweet peas seasonal',
    createdAt: now,
    updatedAt: now,
  },
]
